name: Sarif Upload for HTMLHint

on:
  pull_request:
  push:
    branches-ignore:
      - dependabot/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: htmlhint.sarif
          category: HTMLHint
        if: always()
